# _config.yml

# 网站主题
theme: jekyll-theme-minimal

# 网站标题和描述
title: Hello, Computer Science World!
description: 记录一个计算机本科生的学习与探索之路。

# 设置完整的 URL
URL: "https://liuhangyuwe.github.io"

# 基础路径设置
baseurl: "/software-projects-learning-notes"

# 确保 Jekyll 正确处理仓库里的所有文件和文件夹
include:
  - "01-Project-Management"
  - "02-Frameworks-Libraries"
  - "03-CS-foundation"
  - "04-OS-Implementation"
  - "assets"
  - "LICENSE"

# 为所有 Markdown 文件设置默认值
defaults:
  - scope:
      path: "" # 空字符串表示匹配项目中的所有文件
    values:
      layout: "default"
